//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtDAL.Enty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewDBEnty : DbContext
    {
        public NewDBEnty()
            : base("name=NewDBEnty")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemGroupMaster> ItemGroupMasters { get; set; }
        public virtual DbSet<SubMenuMaster> SubMenuMasters { get; set; }
        public virtual DbSet<UserProfileRight> UserProfileRights { get; set; }
    }
}
