//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtcAction
    {
        public decimal AtcApprovalID { get; set; }
        public Nullable<decimal> AtcID { get; set; }
        public string ActionDoneBy { get; set; }
        public Nullable<System.DateTime> ActionDoneDate { get; set; }
        public string ActionType { get; set; }
        public string Month { get; set; }
        public Nullable<decimal> Year { get; set; }
    }
}
