//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlDiemension
    {
        public int ControlDiemensionID { get; set; }
        public string ControlName { get; set; }
        public string ControlDescription { get; set; }
        public Nullable<int> ControlWidth { get; set; }
        public Nullable<int> ControlHeight { get; set; }
        public int StoreID { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
