//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryMaster
    {
        public CountryMaster()
        {
            this.AtcMasters = new HashSet<AtcMaster>();
            this.AtcMasters1 = new HashSet<AtcMaster>();
            this.CityMasters = new HashSet<CityMaster>();
            this.SupplierMasters = new HashSet<SupplierMaster>();
            this.SupplierMasters1 = new HashSet<SupplierMaster>();
            this.BuyerMasters = new HashSet<BuyerMaster>();
        }
    
        public decimal CountryID { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string FactoryStores { get; set; }
        public string Isthere { get; set; }
    
        public virtual ICollection<AtcMaster> AtcMasters { get; set; }
        public virtual ICollection<AtcMaster> AtcMasters1 { get; set; }
        public virtual ICollection<CityMaster> CityMasters { get; set; }
        public virtual ICollection<SupplierMaster> SupplierMasters { get; set; }
        public virtual ICollection<SupplierMaster> SupplierMasters1 { get; set; }
        public virtual ICollection<BuyerMaster> BuyerMasters { get; set; }
    }
}
