//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutPlanRejectionMaster
    {
        public CutPlanRejectionMaster()
        {
            this.CutPlanRejectHistories = new HashSet<CutPlanRejectHistory>();
        }
    
        public decimal CutPlanRejectionID { get; set; }
        public string CutplanRejection { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CutPlanRejectHistory> CutPlanRejectHistories { get; set; }
    }
}
