//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutplanRefPattern
    {
        public decimal CutPlanRef_PK { get; set; }
        public Nullable<decimal> CutID { get; set; }
        public string Refpattern { get; set; }
        public string AddedBy { get; set; }
        public string Addeddate { get; set; }
    }
}
