//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutPlanMarkerSizeDetail
    {
        public decimal CutPlanSize_PK { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Ratio { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<decimal> CutPlan_PK { get; set; }
        public Nullable<decimal> CutPlanMarkerDetails_PK { get; set; }
    }
}
