//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutPlanMarkerDetail
    {
        public decimal CutPlanMarkerDetails_PK { get; set; }
        public Nullable<decimal> CutPlan_PK { get; set; }
        public string MarkerNo { get; set; }
        public Nullable<decimal> NoOfPc { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> MarkerLength { get; set; }
        public string LayLength { get; set; }
        public Nullable<decimal> NoOfPlies { get; set; }
        public Nullable<decimal> CutPerPlies { get; set; }
        public Nullable<decimal> Cutreq { get; set; }
        public Nullable<decimal> Tolerancelength { get; set; }
        public Nullable<decimal> TotalfabReq { get; set; }
        public string MarkerDetAddedBy { get; set; }
        public Nullable<System.DateTime> MarkerDetAddedDate { get; set; }
        public string PatternAddedBy { get; set; }
        public Nullable<System.DateTime> PatternAddedDate { get; set; }
        public string PaternMarkerName { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public string IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
