//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutPlanRejectHistory
    {
        public decimal CutplanRejectionDetailID { get; set; }
        public Nullable<decimal> Cutplan_PK { get; set; }
        public Nullable<decimal> CutPlanRejectionID { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual CutPlanMaster CutPlanMaster { get; set; }
        public virtual CutPlanRejectionMaster CutPlanRejectionMaster { get; set; }
    }
}
