//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndbitInventory
    {
        public decimal Endbit_Pk { get; set; }
        public Nullable<decimal> Roll_Pk { get; set; }
        public Nullable<decimal> Skudet_pk { get; set; }
        public Nullable<decimal> Location_pk { get; set; }
        public Nullable<decimal> OnHandQty { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> DeliveredQty { get; set; }
        public string RefNum { get; set; }
        public Nullable<decimal> Inventoryitem_pk { get; set; }
    }
}
