//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionAtcList
    {
        public decimal ExceptionID { get; set; }
        public string AtcNum { get; set; }
        public Nullable<decimal> AtcID { get; set; }
    }
}
