//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraRequestReason
    {
        public decimal ExtraRequestReasonID { get; set; }
        public string Reason { get; set; }
        public string IsActive { get; set; }
        public string UsedIn { get; set; }
    }
}
