//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraBOMRequestDetail
    {
        public decimal ExtraBOMDetail_PK { get; set; }
        public Nullable<decimal> Skudet_PK { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> ExtraBOM_PK { get; set; }
    
        public virtual ExtraBOMRequestMaster ExtraBOMRequestMaster { get; set; }
        public virtual SkuRawmaterialDetail SkuRawmaterialDetail { get; set; }
    }
}
