//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricInLocation_tbl
    {
        public decimal FabLocationId { get; set; }
        public Nullable<decimal> AtcId { get; set; }
        public Nullable<decimal> OurStyleId { get; set; }
        public Nullable<decimal> Location_pk { get; set; }
        public Nullable<decimal> SkuDet_PK { get; set; }
        public string ColorName { get; set; }
        public string ColorCode { get; set; }
        public string ItemColor { get; set; }
        public string LocationName { get; set; }
        public string ITemdEscription { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string IsClosed { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> CutQty { get; set; }
        public Nullable<decimal> TotalFabConsumed { get; set; }
        public Nullable<decimal> BomConsumption { get; set; }
        public Nullable<decimal> MarkerConsumption { get; set; }
        public Nullable<decimal> ActualConsumption { get; set; }
        public Nullable<decimal> OverConsumed { get; set; }
        public Nullable<decimal> OverConsumedPer { get; set; }
    
        public virtual AtcDetail AtcDetail { get; set; }
    }
}
