//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricMissing
    {
        public decimal FabricMissingID { get; set; }
        public Nullable<decimal> SkuDetPK { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public Nullable<decimal> MissingQty { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Level1ApprovedBY { get; set; }
        public Nullable<System.DateTime> Level1ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public string IsLevel1Approved { get; set; }
        public string IsDeleted { get; set; }
        public string IsApproved { get; set; }
    
        public virtual AtcDetail AtcDetail { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual SkuRawmaterialDetail SkuRawmaterialDetail { get; set; }
    }
}
