//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemGroupMaster
    {
        public ItemGroupMaster()
        {
            this.ExtDeliveryTokens = new HashSet<ExtDeliveryToken>();
            this.Template_Master = new HashSet<Template_Master>();
        }
    
        public decimal ItemGroupID { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemGroupDescription { get; set; }
    
        public virtual ICollection<ExtDeliveryToken> ExtDeliveryTokens { get; set; }
        public virtual ICollection<Template_Master> Template_Master { get; set; }
    }
}
