//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabChargeDetail
    {
        public decimal LabReqDetID { get; set; }
        public Nullable<decimal> AtcID { get; set; }
        public Nullable<decimal> LabCharge { get; set; }
        public Nullable<decimal> LabRequestID { get; set; }
        public string Remark { get; set; }
    
        public virtual LabRequestMaster LabRequestMaster { get; set; }
        public virtual AtcMaster AtcMaster { get; set; }
    }
}
