//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkerMadeMaster
    {
        public decimal CuttingMarkerMadeID { get; set; }
        public string MarkerMade { get; set; }
        public bool IsActive { get; set; }
    }
}
