//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCR_Master
    {
        public decimal MCR_Pk { get; set; }
        public string MCR_no { get; set; }
        public Nullable<decimal> Location_pk { get; set; }
        public Nullable<decimal> Atc_Id { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string TransferBy { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ConfirmBy { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string IsTransfer { get; set; }
        public string IsReceived { get; set; }
        public string IsApproved { get; set; }
        public string IsConfirmed { get; set; }
        public Nullable<decimal> ToLocation_pk { get; set; }
    }
}
