//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurStyleDeptCM
    {
        public decimal OyurStyleCMID { get; set; }
        public Nullable<decimal> Location_pk { get; set; }
        public Nullable<decimal> AtcWorldLocation_PK { get; set; }
        public Nullable<decimal> DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public Nullable<decimal> DeptCM { get; set; }
        public Nullable<decimal> ProducedGarment { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> DeptSAM { get; set; }
        public Nullable<System.DateTime> effDate { get; set; }
        public Nullable<decimal> JCM { get; set; }
    }
}
