//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternStyle
    {
        public PatternStyle()
        {
            this.SampCutReqMasters = new HashSet<SampCutReqMaster>();
            this.SampCutTicketMasters = new HashSet<SampCutTicketMaster>();
        }
    
        public decimal PatternStyleID { get; set; }
        public string StyleName { get; set; }
    
        public virtual ICollection<SampCutReqMaster> SampCutReqMasters { get; set; }
        public virtual ICollection<SampCutTicketMaster> SampCutTicketMasters { get; set; }
    }
}
