//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RackInventoryMaster
    {
        public decimal RackInventory_PK { get; set; }
        public Nullable<decimal> Inventoryitem_PK { get; set; }
        public Nullable<decimal> MrnDet_Pk { get; set; }
        public Nullable<decimal> SkuDet_PK { get; set; }
        public Nullable<decimal> PoDet_PK { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public string ReceivedVia { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
        public Nullable<decimal> Rack_PK { get; set; }
        public string RefNum { get; set; }
        public string IsLast { get; set; }
    }
}
