//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectReqMaster
    {
        public RejectReqMaster()
        {
            this.RejectReqDetails = new HashSet<RejectReqDetail>();
        }
    
        public decimal RejReqMasterID { get; set; }
        public Nullable<decimal> AtcID { get; set; }
        public string AddedBY { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public bool IsAdjusted { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
        public string Reqnum { get; set; }
        public string RejectionType { get; set; }
    
        public virtual ICollection<RejectReqDetail> RejectReqDetails { get; set; }
    }
}
