//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectReqDetail
    {
        public decimal RejectReqID { get; set; }
        public Nullable<decimal> RejFabReqID { get; set; }
        public Nullable<decimal> AllowedQty { get; set; }
        public Nullable<decimal> RejReqMasterID { get; set; }
        public Nullable<decimal> GarmentQty { get; set; }
        public string RejectionType { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
        public string FabreqNum { get; set; }
    
        public virtual RejectReqMaster RejectReqMaster { get; set; }
    }
}
