//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOrderLoanDetail
    {
        public decimal LRODet_Pk { get; set; }
        public Nullable<decimal> LRO_Pk { get; set; }
        public Nullable<decimal> SkuDet_PK { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<double> CUnitPrice { get; set; }
        public Nullable<decimal> InventoryItem_PK { get; set; }
        public Nullable<decimal> PODet_PK { get; set; }
    
        public virtual RequestOrderLoanMaster RequestOrderLoanMaster { get; set; }
    }
}
