//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoInStockMaster
    {
        public RoInStockMaster()
        {
            this.RoInStockDetails = new HashSet<RoInStockDetail>();
        }
    
        public decimal RoInStock_PK { get; set; }
        public Nullable<decimal> SRO_Pk { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<decimal> Location_pk { get; set; }
        public string RoInStockNum { get; set; }
        public string RoInStockType { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual ICollection<RoInStockDetail> RoInStockDetails { get; set; }
    }
}
