//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDebitNoteMaster
    {
        public SalesDebitNoteMaster()
        {
            this.SalesDebitNoteDetails = new HashSet<SalesDebitNoteDetail>();
        }
    
        public decimal SalesDebitMasterID { get; set; }
        public string SalesDebitNUM { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<decimal> Year { get; set; }
        public string Month { get; set; }
        public Nullable<decimal> FromLocation_PK { get; set; }
        public Nullable<decimal> ToLocationPK { get; set; }
        public string IsCompleted { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<SalesDebitNoteDetail> SalesDebitNoteDetails { get; set; }
    }
}
