//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDispatchDetail
    {
        public decimal SampleDispatchID { get; set; }
        public Nullable<decimal> SampCutreqID { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
        public Nullable<decimal> DispatchedQty { get; set; }
        public string DispatchedBy { get; set; }
        public Nullable<bool> ISApproved { get; set; }
        public string Remark { get; set; }
    
        public virtual SampCutReqMaster SampCutReqMaster { get; set; }
    }
}
