//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleFabricEntryMaster
    {
        public decimal SamplingFab_PK { get; set; }
        public string Code { get; set; }
        public string Merch_Name { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public string Qty { get; set; }
        public string Width { get; set; }
        public string Supplier { get; set; }
        public string SuperRef { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AwbNum { get; set; }
        public string Weight { get; set; }
        public string Unit { get; set; }
    }
}
