//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDocumentDetail
    {
        public decimal ShippingDet_PK { get; set; }
        public Nullable<decimal> ShipingDoc_PK { get; set; }
        public Nullable<decimal> Doc_Pk { get; set; }
        public string DocType { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
    
        public virtual DocMaster DocMaster { get; set; }
        public virtual ShippingDocumentMaster ShippingDocumentMaster { get; set; }
    }
}
