//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentHandoverColorSizeDetail
    {
        public decimal ShipmentHOColorDet_PK { get; set; }
        public Nullable<decimal> ShipmentHandOver_PK { get; set; }
        public Nullable<decimal> PoPack_Detail_PK { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> ShipmentHandMaster_PK { get; set; }
    }
}
