//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPOMaster
    {
        public StockPOMaster()
        {
            this.StockMRNDetails = new HashSet<StockMRNDetail>();
            this.StockMrnMasters = new HashSet<StockMrnMaster>();
            this.StockPODetails = new HashSet<StockPODetail>();
            this.StockFreightChargeDetails = new HashSet<StockFreightChargeDetail>();
        }
    
        public decimal SPO_Pk { get; set; }
        public string SPONum { get; set; }
        public Nullable<decimal> AtcId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Supplier_Pk { get; set; }
        public Nullable<decimal> DeliveryTerms_Pk { get; set; }
        public Nullable<decimal> DeliveryMethod_Pk { get; set; }
        public Nullable<decimal> PaymentTermID { get; set; }
        public Nullable<decimal> PaymentModeID { get; set; }
        public Nullable<double> PO_value { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
        public Nullable<decimal> CurrencyID { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Remark { get; set; }
        public string IsApproved { get; set; }
        public string IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> Approveddate { get; set; }
        public string IsSubmitted { get; set; }
        public string ForwardedBy { get; set; }
        public string MarkCompleted { get; set; }
        public Nullable<decimal> DeptPK { get; set; }
    
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual DeliveryTermMaster DeliveryTermMaster { get; set; }
        public virtual PaymentTermMaster PaymentTermMaster { get; set; }
        public virtual ICollection<StockMRNDetail> StockMRNDetails { get; set; }
        public virtual ICollection<StockMrnMaster> StockMrnMasters { get; set; }
        public virtual ICollection<StockPODetail> StockPODetails { get; set; }
        public virtual StockPOMaster StockPOMaster1 { get; set; }
        public virtual StockPOMaster StockPOMaster2 { get; set; }
        public virtual SupplierMaster SupplierMaster { get; set; }
        public virtual ICollection<StockFreightChargeDetail> StockFreightChargeDetails { get; set; }
        public virtual DepartmentMaster DepartmentMaster { get; set; }
    }
}
