//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.ControlDiemensions = new HashSet<ControlDiemension>();
            this.PrinterDetails = new HashSet<PrinterDetail>();
        }
    
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreAddress { get; set; }
    
        public virtual ICollection<ControlDiemension> ControlDiemensions { get; set; }
        public virtual ICollection<PrinterDetail> PrinterDetails { get; set; }
    }
}
