//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempProductionData
    {
        public decimal TempID { get; set; }
        public Nullable<decimal> ArtLocation_PK { get; set; }
        public Nullable<decimal> CutQty { get; set; }
        public Nullable<decimal> SewingQty { get; set; }
        public Nullable<decimal> SortQty { get; set; }
        public Nullable<decimal> WashQty { get; set; }
        public Nullable<decimal> FinishQty { get; set; }
        public Nullable<decimal> AirOutQty { get; set; }
        public Nullable<decimal> ShipQty { get; set; }
        public Nullable<decimal> DOReceiveQty { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<decimal> PoPack_Detail_PK { get; set; }
        public Nullable<decimal> AtcId { get; set; }
        public string AddedBY { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
