//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOMMaster
    {
        public UOMMaster()
        {
            this.AltUOMMasters = new HashSet<AltUOMMaster>();
            this.AltUOMMasters1 = new HashSet<AltUOMMaster>();
            this.ProcurementDetails = new HashSet<ProcurementDetail>();
            this.Template_Master = new HashSet<Template_Master>();
            this.SkuRawMaterialMasters = new HashSet<SkuRawMaterialMaster>();
            this.StocPOForODOOs = new HashSet<StocPOForODOO>();
            this.InventoryMasters = new HashSet<InventoryMaster>();
        }
    
        public decimal Uom_PK { get; set; }
        public string UomCode { get; set; }
        public string UomName { get; set; }
        public string UomType { get; set; }
    
        public virtual ICollection<AltUOMMaster> AltUOMMasters { get; set; }
        public virtual ICollection<AltUOMMaster> AltUOMMasters1 { get; set; }
        public virtual ICollection<ProcurementDetail> ProcurementDetails { get; set; }
        public virtual ICollection<Template_Master> Template_Master { get; set; }
        public virtual ICollection<SkuRawMaterialMaster> SkuRawMaterialMasters { get; set; }
        public virtual ICollection<StocPOForODOO> StocPOForODOOs { get; set; }
        public virtual ICollection<InventoryMaster> InventoryMasters { get; set; }
    }
}
