//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrongInventoryDocument
    {
        public decimal WrongInvtDoc_PK { get; set; }
        public string DocumentType { get; set; }
        public Nullable<decimal> User_PK { get; set; }
        public string DocumentNumber { get; set; }
        public string Explanation { get; set; }
        public string ActionRequired { get; set; }
        public string ITRemark { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public string Reqnum { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ForwardedBY { get; set; }
    }
}
