//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModelAtcWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtJobContractMaster
    {
        public decimal ArtJobContract_PK { get; set; }
        public Nullable<decimal> JobContract_PK { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
        public Nullable<decimal> CM { get; set; }
        public string JobContractNum { get; set; }
        public string AtcNum { get; set; }
        public string OurStyle { get; set; }
        public Nullable<decimal> AtcID { get; set; }
    }
}
