//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModelAtcWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtLaySheetDetail
    {
        public decimal ArtLaySheetDet_PK { get; set; }
        public Nullable<decimal> LaySheetDet_PK { get; set; }
        public Nullable<decimal> LaySheet_PK { get; set; }
        public Nullable<decimal> Roll_PK { get; set; }
        public Nullable<decimal> NoOfPlies { get; set; }
    }
}
