//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModelAtcWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASQShuffleDetailsAtc
    {
        public decimal AsqShuffleDet_PK { get; set; }
        public Nullable<decimal> AsqShuffle_PK { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public Nullable<decimal> FromPOPackDet_PK { get; set; }
        public Nullable<decimal> ToPOPackDet_PK { get; set; }
        public Nullable<decimal> AddedQty { get; set; }
        public Nullable<decimal> RevisedQtyofFromPOPackDet_PK { get; set; }
        public Nullable<decimal> RevisedQtyofToPOPackDet_PK { get; set; }
        public Nullable<decimal> ArtAsqShuffleDet_PK { get; set; }
    }
}
