//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModelAtcWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASQShuffleMasterAtc
    {
        public decimal AsqShuffle_PK { get; set; }
        public Nullable<decimal> FromPOPackID { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public string AddedBY { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string AsqShuffleNum { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
