//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWebApp.DataModelAtcWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmDozmaster
    {
        public decimal CmDozId { get; set; }
        public decimal Atc_Id { get; set; }
        public decimal OurStyleId { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public decimal CmDoz { get; set; }
        public Nullable<decimal> Location_pk { get; set; }
        public decimal User_PK { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string HostName { get; set; }
        public string MachineIP { get; set; }
    
        public virtual LocationMaster_tbl LocationMaster_tbl { get; set; }
    }
}
